adonisjs/core

- src/Server/index.js
- test/integration/basic-server.spec.js
Implement feature https://github.com/adonisjs/adonis-framework/issues/4
I have also make this spec more consistent.
--
**Alternative**
```javascript
Server.prototype.start = function (port, host) {
host = host || '0.0.0.0'
this.Logger.info('serving app on port %s', port)
this.serverInstance.listen(port, host)
}
```
If we implement the alternative we don't need to change tests.
--
Mirror PR: https://github.com/adonisjs/adonis-app/pull/1
> add possibility to bind to an host

- src/Encryption/index.js
- test/unit/encryption.spec.js
The Encryption class didn't work properly, so i fixed it and implemented it like [Laravel](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Encryption/Encrypter.php) did.
It now uses initialization vector for the encryption.
Unfortunately it's not compatible with Laravels encrypted data, because they use [serialize](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Encryption/Encrypter.php#L66)/[unserialize](https://github.com/laravel/framework/blob/5.2/src/Illuminate/Encryption/Encrypter.php#L106).
> Add initialization vector to Encryption

- src/View/loader.js
- test/unit/app/views/extends.nunjucks
- test/unit/app/views/include.nunjucks
- test/unit/app/views/subviews/index.nunjucks
- test/unit/app/views/subviews/master.nunjucks
- test/unit/view.spec.js
Breaking Change Friendly :heavy_check_mark:
This PR allow us to use a . instead of a / to define a view.
Examples:
```javascript
// Routing
Route.on('/').render('frontend.pages.index')
```
```javascript
// Templating
{% extends 'frontend.layouts.app' %}
{% include 'frontend.partials.navbar' %}
```
> chore(view): let us use . instead of / to define a view

- package.json
The developer of Cheerio has unpublish the version 0.21.0.
We should remove this version from our package.json file.
More information: https://github.com/cheeriojs/cheerio/issues/872
> chore(package): rollback cheerio version

- src/Server/index.js
- test/unit/server.spec.js
Hi!
I only let the listen() method to return the server instance (like the official server.listen())
So we can do:
```js
let server = Server.listen(Env.get('HOST'), Env.get('PORT'))
// Use server with socket.io configuration...
```
I'm aware about `Server.getInstance()` but I wanted to know your point of view comparing to the official behaviour.
PS: I added the test associated to the feature
> feat: Make Server.listen() return the http.Server instance

- src/Helpers/index.js
- test/unit/helpers.spec.js
Hi,
```js
// app/Http/Controllers
Route.get('*', 'AppleController.eat')
```
```js
// package.json
"autoload": {
"App": "./app"
}
```
I get this error when I added a controller starting with App:
```
Cannot find module '/Users/Atinux/Projets/MyAdonisApp/appleController'
```
I found the bug in the `Helpers.makeNameSpace()` method.
I replaced:
```js
toPath.startsWith(appNameSpace)
```
to
```js
toPath.startsWith(`${appNameSpace}/`)
```
So now it makes sure to verify that the namespace has a slash after.
I also added a test to verify any regression for this bug 🔥
> fix: Fix bug when using a namespace starting with App

- providers/ServerProvider.js
I think it better server to be singleton as server only need run once until it die.
and with this we can get server instance from anywhere.
if server provider using `bind` we will be hard to get server instance as every time we call `use('Adonis/Src/Server')`, server will be get new instance
> make server to be singleton

- package.json
- src/Session/index.js
Hi there,
This week a new version of the [uuid](https://github.com/kelektiv/node-uuid) module got released. The old module which was available by the name [node-uuid](https://www.npmjs.com/package/node-uuid) got deprecated and will show error message upon every install of the module.
To get rid of those install errors I've created this **automated pull request**. I've run some checks against your code base to test whether you're using one of the [deprecated apis](https://github.com/kelektiv/node-uuid/commit/5ae7287fc935eb55ef39133e4be17ef623ca000e), but this isn't the case.
Please test the changes against your code. I didn't run any tests and therefore can't guarantee that it isn't breaking. You can also just close this pr if you don't want to update your module.
In case there's already …
> Update uuid to version 3.0.0

- src/View/Form/index.js
- test/unit/view.form.spec.js
Label does not have `name` attribute, it uses `for` attribute which needs to be the same as input id.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label
> fix(view): fix label default attribute, use for instead of name

- README.md
The table of content is useless in case of a small README. That's our case!
> doc(readme): remove the table of content

- src/Route/helpers.js
- test/unit/route.spec.js
We should be able to prefix route's group without writing the first
slash.
Example:
```javascript
Route.group('v1', function () {
// Some routes...
}).prefix('api/v1') // before it should be .prefix('/api/v1')
```
Closes: https://github.com/adonisjs/adonis-framework/issues/415
> fix(routing): allow to prefix a group without a starting slash

- src/Exceptions/index.js
- src/File/index.js
- test/unit/file.spec.js
This pull request adds a delete method on the `File` class.
This is helpful for when files are uploaded to the server to be dealt with and you want to discard them afterwords without calling `fs.unlink` manually.
> Add delete method on File class

- src/Route/Resource.js
- test/unit/route.spec.js
When a resource has defined global (wildcard) middleware and route-specific middleware only global middleware is used.
This PR introduces fix for this - when both, global and route-specific middlewares are defined they will be merged together.
> Merge resource middleware

- src/Response/index.js
Problem when we use redirect settings with "sendParams=true", for example: 
```
response.redirect("/some-amazing-stuff", true, 301)
```
But if given url doesn't contain params, Adonis will redirect us to "/some-amazing-stuff?null". 
I think it's not desired behavior, especially in terms of SEO...
> Fix "?null" in redirect URL

- src/Route/Group.js
- src/Route/index.js
- test/unit/route.spec.js
This PR adds a `namespace` function to Route and Group.
This feature allows you to specify a folder on a group, so you do not have to repeat the same path on every route.
**Example:**
You have multiple Controller grouped inside folders: 
- app/Controller/Http/Api/v1/UserController.js
- app/Controller/Http/Api/v1/RoleController.js
With this PR you can simplify the route definition from this:
```js
Route.group(() => {
Route.resource('/users', 'Api/v1/UserController')
Route.resource('/roles', 'Api/v1/RoleController')
}).prefix('api/v1')
```
to this:
```js
Route.group(() => {
Route.resource('/users', 'UserController')
Route.resource('/roles', 'RoleController')
}).prefix('api/v1').namespace('Api/v1')
```
> Add namespace function to Route and Group

- package.json
- providers/AppProvider.js
- src/Hash/Drivers/Argon.js
- src/Hash/Drivers/Bcrypt.js
- src/Hash/Drivers/index.js
- src/Hash/Facade.js
- src/Hash/Manager.js
- src/Hash/index.js
- test/unit/hash.spec.js
Hey 👋 
This PR completely change how Hash works in Adonis without creating any breaking change.
The new driver system will use `bcrypt` by default if there isn't any configuration (so current codebase will not break).
The new code will let you configure the driver (`bcrypt` or `argon`) via the file `config/hashing.js`. See the example bellow.
```js
// config/hashing.js
module.exports = {
driver: 'bcrypt',
bcrypt: {
round: 10
}
argon: {
timeCost: 4,
memoryCost: 13,
parallelism: 2
}
}
```
If this modification is accepted, I'll provide another PR to add this configuration file to `fullstack`, `api` and `slim` blueprint. I'll also update the current doc to reflect the change.
> [Feature] Provide a way to use Argon instead of Bcrypt for hashing

- src/View/globals.js
- test/unit/views.spec.js
Quite often I use the `route` view global, and I forget to pass the ID or any other param to the second argument of the global.
For example:
```blade
<a href="{{ route('posts.show') }}">...</a>
```
But as the ID is missing, I get this unclear error message:
> `Expected "id" to be a string`
So I've created an error handler when calling `Route.url()` from the view provider to create a slightly more specific error message.
> Change error message for the errors caused by the "route.url" view global

- src/Exception/BaseHandler.js
Adding a link to the forum on the BaseExceptionHandler. For example, if the error message is response.seend is not a function, the user will get a link pointing to https://forum.adonisjs.com
Following this pull request : https://github.com/adonisjs/adonis-framework/pull/969
Only the discord have been added
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we …
> Croquet mickael patch 1

- src/Env/index.js
The `Env.load()` is not void method. This PR just update the docblock.
> Fix Env.load() docblock

- test/unit/route.spec.js
This PR is the starting point to prevent duplicated route name. I don't have a fix for this failing test at the moment since you register the route before assigning it a name. I need your opinion if this is an issue, and when you want to throw an exception ?
```
Route.get('/users', () => '').as('users.index')
Route.get('/users', () => '').as('users.index')
```
> feat: duplicate route name failing test

- src/Route/Manager.js
- test/unit/route.spec.js
Pass query object into route helper second argument to make query string.
Follow issue: [#716](https://github.com/adonisjs/adonis-framework/issues/716)
```javascript
route('posts.show', { id: 1, query: { foo: 'bar' } })
// => /post/1?foo=bar
```
```html
<a href="{{ route('posts.show', { id: 1, query: { foo: 'bar' } }) }}">Show post</a>
```
> Allow pass query string into route helper.

- README.md
#1160
Purely an update to the shields.io license image to show "MIT License" as it currently shows "Package not found".
An updated shields.io URL for the license-image in README.md which tracks the repository license and shows the relevant image.
Just a note to the maintainers regarding shields.io rate limits:
> If your GitHub badge errors, it might be because you hit GitHub's rate limits. You can increase Shields.io's rate limit by adding the Shields GitHub application using your GitHub account.
It's a …
> fixed the license badge in README.md pointing to an invalid URL

- src/Ignitor/HttpServer/index.ts
The Promise constructor doesn't automatically catch errors if its handler
function is async. Use try/catch to avoid unhandled rejections.
If the server is closed because the port is already in used, use a
non-zero exit code and log it as an error.
> fix(server): correctly handle errors on listen

- templates/config/hash.txt
Hey! 👋 
This PR swap the default hasher to `argon`.
It also use an environement variable since you may want to use another driver when testing.
> refactor: use Env variable to define the hasher and default to argon

- .github/ISSUE_TEMPLATE/bug_report.md
Fix typo in the Bug Report GitHub template.
> Fix typo in bug_report.md

- package.json
This allows to `require('@adonisjs/core/standalone')` instead of having
to deeply grab it from the build directory.
Provide a star export fallback for backwards-compatibility.
> feat: provide subpath exports for public API

- src/Ignitor/index.ts
- test/ignitor.spec.ts
The URL is converted to an absolute path, so the rest works as before.
This is to enable applications written in ESM to do `new Ignitor(import.meta.url)`
as the `__dirname` variable doesn't exist in ESM.
> feat: support file URL in Ignitor

- commands/index.ts
- package.json
This should be compatible with both ESM and Yarn 2 (which sadly doesn't
support the exports field).
> fix: export commands with full paths

- commands/ListRoutes/ListRoutes.ts
- commands/ListRoutes/PrettyRenderer.ts
- commands/ListRoutes/TableRenderer.ts
- test/commands/list-routes-json.spec.ts
- test/commands/list-routes-pretty.spec.ts
The PR contains following changes/improvements.
- Adding license docblock to all the files. Since, AdonisJS is not only maintained by me anymore, I have removed my name and email from the license block.
- Rename all instances of `serializedRouter` with `serializedRoutes`.
- Instead of passing too many arguments to the renders. I am passing the command instance to them.
- Replaced method bind calls like `this.colors.red.bind(this.colors)` with just the color name. Otherwise, we are creating 6-7 new methods.
- Move `getTerminalWidth` method to the PrettyListRenderer class. I believe, the renderer should be concerned with finding the columns width and not the ListRoute command.
- Introduce a new flag `maxWidth` to control the rendering width for the pretty list.
This PR does change the JSON …
> Cleanup code for the list routes command

- commands/ListRoutes/index.ts
As discussed here: https://github.com/Julien-R44/adonis-vscode-extension/issues/4
When many routes are defined, ListRoute does not wait until the queue of things to be printed is empty before killing the process, so we have to add stayAlive
> fix: add stayAlive to ListRoutes command

- templates/config/hash.txt
Changes the comment for default hasher.
Here it is saying inside the comment that ```argon``` is the default hasher. But the default prop is set to ```scrypt```
> fix: default hasher mismatch fix

- .github/CONTRIBUTING.md
Just adding a "#" in front of the contributing.md content table links. Currently it's causing a 404 on Github.
> docs(contributing): fix content table link

- commands/make/_base.ts
- modules/ace/commands.ts
Add a method `makeUsingStub` to Ace BaseCommand.
```ts
this.makeUsingStub(stubPath, stubState, stubsRoot)
```
Not sure about this PR. It doesn't seem very clean to me because we have a particular OOP architecture here and so I was forced to duplicate the code in `ListCommand`, and also to leave the `stubsGenerator` property in public. (that's also why I preferred to using composition here by extracting the StubGenerator class)
I almost went further and refactored it maybe with Mixins (to remove the fact that ListCommand implements BaseCommand) because it seems to be problematic 
But I prefered to keep it simple and just duplicate for the moment because it's a very small change
Let me know what you think!
> feat: add `makeUsingStub` to BaseCommand

- commands/configure.ts
- package.json
- tests/commands/configure.spec.ts
Add a `configure.installPackages` method that use `antfu/install-pkg` under the hood https://github.com/antfu/install-pkg. Doesnt bring any heavy dependency
Output :
> feat: add `Configure.installPackages` method

- templates/config/cors.txt
Hello 👋 
Is there a specific reason that PATCH was not included as a default method for the CORS configuration? It took me a little bit of stumbling around to figure out why PATCH requests weren't working for me. It was surprising to me that this was not a default. 
(not positive here, since this is a template that would likely only affect new projects, I'm considering it a new feature).
The docs would need to be updated too if this change were to be …
> change: add PATCH as a default method for CORS headers

- stubs/make/command/main.stub
- stubs/make/controller/api.stub
- stubs/make/controller/main.stub
- stubs/make/controller/resource.stub
- stubs/make/listener/for_event.stub
- stubs/make/middleware/main.stub
- stubs/make/provider/main.stub
- tests/stubs/make_controller.spec.ts
- tests/stubs/make_listener.spec.ts
- tests/stubs/make_middleware.spec.ts
- tests/stubs/make_provider.spec.ts
Hey there! 👋🏻 
This PRs use the `import type` import when possible for all stubs.
> fix(stubs): use "import type" when possible

- commands/make/controller.ts
#4419
- [ x] 🐞 Bug fix (a non-breaking change that fixes an issue)
Resolves #4419.
The `--api` & `--resource` argument descriptions of `make:controller` were swapped.
I just swapped them so that the descriptions make sense again.
`--resource` is the one that generates `edit` & `create` methods.
- [x ] I have linked an issue or discussion.
> fix(commands): swapped description -a & -r for make:controller

- commands/build.ts
- commands/serve.ts
- package.json
- tests/commands/build.spec.ts
- tests/commands/serve.spec.ts
Passing assembler hooks defined in RC file as arguments to the Assembler classes from `node ace build` and `node ace serve` commands
> feat: add hooks for build and dev server

- src/internal_helpers.ts
- tests/commands/serve.spec.ts
Users can now totally disable the assets bundler logic integrated in the assembler, and this from the RCFile : 
```ts
// adonisrc.ts
export default defineConfig({
// Disable assembler built-in assets bundler
assetsBundler: false, 
assembler: {
onDevServerStarting: [
// Let @adonisjs/vite manage the assets bundling itself
() => import('@adonisjs/vite/build_hook')
]
}
})
```
This is useful in our case, because with the next Vite integration, adonisjs/vite itself will launch the vite dev server
One thing to note : It's weird to set `assetsBundler` to false when you want to use Vite. It's not logical at all for users who don't know about internals of Adonis. But for the moment, we don't have much choice. Later, if our new Vite integration is successful, we should be able to remove all asset …
> feat: do not run assets bundler when explicitely disabled in rc file

- modules/ace/codemods.ts
- tests/ace/codemods.spec.ts
Add `registerVitePlugin` and `registerJapaPlugin` methods to the `Codemods` class
> feat: add registerVitePlugin and registerJapaPlugin

- modules/ace/codemods.ts
- tests/ace/codemods.spec.ts
Two things : 
- add a `getTsMorphProject()` method on `Codemods` class. so that users can make their own codemods as explained in https://github.com/adonisjs/assembler/pull/74
```ts
export async function configure(command: Configure) {
const codemods = await command.createCodemods()
const project = await codemods.getTsMorphProject()
// can do whatever I want
project.getSourceFileOrThrow('file.ts').addImportDeclaration({
moduleSpecifier: 'ts-morph',
namedImports: ['Project'],
})
}
```
- Refactoring the Codemods class so as to create just one instance of `ts-morph` and `CodeTransformer`. Creating an instance of `ts-morph` is a costly operation
> feat: add getTsMorphProject method

- README.md
Found a broken link in the readme.md for the core project, that it was incorrectly pointing to a (presumably older) wrong location for the contribution docs.
I have updated the link.
No linked issues that I'm aware of, it's a small documentation update.
Updates broken link in documentation
> fix(docs): update broken link 

- commands/serve.ts
- package.json
- tests/commands/serve.spec.ts
Depends on https://github.com/adonisjs/assembler/pull/77. Must be merged and released first
---
Add the flag `--hmr` that will be passed to Assembler DevServer class
`--hmr` and `--watch` cannot be used together, since `--hmr` also watch files. so we display an error if we use them together
> feat: add `--hmr` flag for the `serve` command

- commands/env/add.ts
- modules/ace/codemods.ts
- package.json
- tests/ace/codemods.spec.ts
- tests/commands/add.spec.ts
- tests/commands/configure.spec.ts
- tests/commands/env_add.spec.ts
Okay, so this is something that's been bugging me for a long time. I'm often in the middle of development, and I realize that I need to add an environment variable. And then I have to open 3 different files in my editor: `env.example`, the `.env`, and the `start/env.ts` to add my new variable. 
Then I find myself with lots of new tabs open in my IDE, which is a mess. And even without that, it's boring to do manually.
That's why I suggest the `env:add` command, which works like this: 
```
node ace env:add MY_VARIABLE value --type=string
```
executing this command will add the variable to the `.env.example`, `.env` and `start/env.ts` files. The variable name will be converted to SCREAMING_SNAKE_CASE. 
```
node ace env:add
```
executing the command without any arguments/flags will display …
> feat: add env:add command

- commands/add.ts
- commands/build.ts
- modules/ace/codemods.ts
- package.json
- tests/commands/add.spec.ts
#4568 
Add support for `node ace add` when using `yarn@berry`.
It is supported almost out of the box, it was just filtered out.
`@adonisjs/assembler` was updated to include changes from https://github.com/adonisjs/assembler/pull/79.
> feat: yarn berry support

- commands/add.ts
https://github.com/adonisjs/core/issues/4606
Resolves #4606, adding support for bun.
> Add bun support for ace add
