readme.md

Updated the licence date

---

readme.md

Add License and Downloads badges.
I have also switch all badges to shields.io and flat design.

update shields badges

---

readme.md

Reverts adonisjs/adonis-framework#42

Revert "Updated the licence date"

---

package.json

As discussed with @thetutlage we are going to follow a convention about commit message.

feat(package.json): make the repository commitizen-friendly

---

src/Route/resource.js
test/unit/route.spec.js

Hi,
I would like to add this new feature based on [Rails Routing](http://guides.rubyonrails.org/routing.html#adding-more-restful-actions). This feature allows to create more RESTful Actions.
Let me know if you like it :smile:

feature-collection-and-member-routes

---

CONTRIBUTING.md
README.md

fix broken links to docs

---

CONTRIBUTING.md
README.md

Hi,
I updated the links to link to the 3.1 docs!
Great job with Adonis Framework 🔥

style(): Fix links to documentation

---

src/Server/index.js

Makes it a little bit easier to debug.

Add method to Route not found exception

---

package-lock.json
package.json
src/Env/index.js
test/unit/env.spec.js

Added Env.getOrFail method.

---

src/Server/index.js

Adding a code to this exception make it easier to handle in the exception handler.

feat(server): add code to 404 exception

---

.travis.yml
package.json

Only run it on CI so that local test runs don't fail.

fix(package): do not run always run coverage

---

README.md

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

HTTPS is always better :)

---

src/Exception/BaseHandler.js

Adding a link to the forum on the ``BaseExceptionHandler``. For example, if the error message is ``response.seend is not a function``, the user will get a link pointing to [https://forum.adonisjs.com](https://forum.adonisjs.com/search?q=response.seend%20is%20not%20a%20function)

feat(exception): Add forum link

---

CONTRIBUTING.md

This PR just update Contribution URL, because the old URL no longer exists.

Update Contribution URL

---

README.md

* Add PR welcoming badge within the `README` file pointing to the `contributing.md` file 
* Made the `fossa` badge markdown format the same as that of the ones above.

Add PR welcoming badge and a minor markdown fix

---

README.md

I fixed a short list of typos and grammatical errors in README file.

Fixed few typos and grammar

---

README.md

I'm "that guy" who is just making readme changes... 🙈
The readme is typically a "first impression" for the codebase. Let's make it as good as possible!
Purely grammatical changes to the readme.
I'm just learning Adonisjs... amazing work! Hope to contribute for real some day! 💯

Fix some grammar issues

---

README.md

- I removed unneeded spaces in README.md, I applied the pattern of separating headers with an empty line.
- I've added alternative text to the Typescript support image.
- I fixed the profile of the author (@thetutlage), which was with a nonexistent user.
Changes in README.md.

fix: fixes the author's profile, add alt text in ts image, add blank line after headings in README.md

---

test/unit/request.spec.js

The current test about Content Negotiation is wrong and make the testing suite break.

test(Request): correct test about Content Negotiation

---

README.md

Fix link that redirect to CONTRIBUTING.md internal page in adonis-framework repository.

fix CONTRIBUTING.md link

---

config/static.txt

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

Enable serving static files by default for web application

---

CONTRIBUTING.md

Some links in the CONTRIBUTING.md file gave 404s, so I updated them. I looked around the official adonis.js website for the links and replaced them in the markdown file. 
***None of the above, just updating some documentation.***
***The others don't apply really, since I'm just updating some docs.***

docs(Contributing): fix links to use #

---

templates/config/cors.txt

Fixing small typos in cors.ts.

Small typos in cors.ts

---

src/Bindings/Repl.ts

Fixed a typo in `repl.ts` file

Fix typo in repl.ts

---

commands/index.ts
package.json

Also define more exports for backwards compatibility.

feat: support subpath exports for commands

---

templates/config/hash.txt

see #3169
fix comment: argon is the default hasher, not bcrypt.
I got some timeout errors on local tests, 14 failed because of that and i dont know how to fix this issue for now.
```
total         : 103
failed        : 14
passed        : 89
duration      : 30s
Ignitor | Http
✖ call ready hook on providers before starting the http server
Test timeout after 2000 milliseconds
✖ start http server to accept incoming requests
Test timeout after 2000 milliseconds …
```

docs(config templates): fix comment: argon is the default hasher

---

README.md

This PR fixes tiny issue with link to Contributing.md
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

Fixed link for CONTRIBUTING.md

---

templates/contracts/env.txt
templates/env.txt

Every time when creating new project one of the first commits is fixing linting rules on some of the default files. This PR fixes some templates that have linting errors in there
-

style: fix linter errors in templates

---

templates/config/app.txt
templates/config/drive.txt
templates/contracts/env.txt

When creating fresh project, then code lint fails for it out-of-box
This PR makes it so, that `npm run lint` wouldn't return any errors for fresh project
\-

style: fix code-style typos in templates

---

templates/config/drive.txt

see: https://github.com/adonisjs/docs.adonisjs.com/pull/150

docs: add comment in config/drive.ts for minio

---

templates/config/hash.txt

Hey there! 👋🏻 
This PR adds the `scrypt` configuration.
Related: https://github.com/adonisjs/hash/pull/9

feat(hash): add scrypt config

---

README.md

Fix badge for test CI
This only fix the badge in README broken since shield.io change the endpoint for the badge

[ci skip] Fix badge for CI test in Readme
